CREATE TABLE IF NOT EXISTS users
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    roles VARCHAR(100)
);

GRANT ALL ON TABLE users TO postgres WITH GRANT OPTION;